backend:
  name: git-gateway
  branch: ghp-version

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Author",
          name: "author",
          widget: "string",
          default: "Uprava škole",
        }
      - { label: "Categories", name: "categories", widget: "list" }
      - {
          label: "Featured",
          name: "featured",
          widget: "boolean",
          default: false,
        }
      - { label: "Featured Image", name: "featured_image", widget: "image" }
      - {
          label: "Thumbnail",
          name: "thumbnail",
          widget: "hidden",
          pattern:
            [
              "^{{featured_image}}$",
              "Thumbnail is automatically set to Featured Image",
            ],
        }
      - {
          label: "Excerpt",
          name: "excerpt",
          widget: "hidden",
          pattern:
            [
              "^{{body | strip_html | truncatewords:30}}$",
              "Excerpt is automatically generated from body",
            ],
        }
      - { label: "Body", name: "body", widget: "markdown" }
