name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # or master, or whichever branch you want to deploy from

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0' # Match the same Ruby version as Netlify
          bundler-cache: true   # Caches dependencies for faster builds

      - name: Build site
        run: |
          bundle install
          bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          # Optional settings below
          # publish_branch: gh-pages
          # cname: devetaosnovna.ba